### ISSUE TITLE
HTML assignment  https://github.com/Abdul-Azeez/HTML/

### ISSUE THREAD

**Issue by Abdul-Azeez** [Abdul-Azeez/HTML#1]

**Comment by ashubuddy89** [comment]
please see design again.
check indentation.
input boxes should be active (focus) when click on label.
input checkbox/radio button should be checked when click on label.
Remove extra closing tag from "Your favourite color:"
Reset button is not working.
use only single form.

**Comment by Abdul-Azeez** [comment]
Done. Please confirm.

**Comment by ashubuddy89** [comment]
looking fine now...
